create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  image_url text not null default '',
  category text not null default '',
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);
alter table public.products enable row level security;
drop policy if exists "Allow public read products" on public.products;
create policy "Allow public read products"
on public.products for select to anon, authenticated using (true);
